modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "github_test_mod"
version = "${version}"
displayName = "GitHub Test Mod"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.github_test_mod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.github_test_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.github_test_mod]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
