name: build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle & Loom
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
          gradle-version: wrapper

      - name: Build
        run: |
          chmod +x gradlew
          TEST_BUILD=${{ github.event.pull_request.number || github.run_number }} ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ github.event.pull_request.number || github.run_number }}
          path: |
            fabric/build/libs/
            forge/build/libs/