name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Loom Cache
        uses: actions/cache@v4
        with:
          path: "**/.gradle/loom-cache"
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: "${{ runner.os }}-gradle-"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Validate Gradle Wrapper Integrity
        uses: gradle/wrapper-validation-action@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build
        run: TEST_BUILD=${{ github.event.number }} ./gradlew build

      - name: Generate Javadoc
        run: ./gradlew javadocAll

      - name: Upload Javadoc
        uses: actions/upload-artifact@v4
        with:
          name: javadoc-${{ github.event.number }}
          path: docs/


      - name: Capture Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ github.event.number }}
          path: |
            fabric/build/libs/
            forge/build/libs/